image: docker:stable-dind

stages:
  - build

variables:
  IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_DRIVER: overlay2


build_images:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --tag $IMAGE:$CI_BUILD_REF --tag $IMAGE:latest -f deploy/Dockerfile .
    - docker push $IMAGE:$CI_BUILD_REF
    - docker push $IMAGE:latest